swagger: "2.0"
info:
  version: 1.0.0
  title: rest_api_2
  description: My cool app
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


paths:
  /suggestions:
    get:
      tags:
        - Movie suggestions
      description: Show movies suggestions
      responses:
        200:
          description: Returns all suggestions
      parameters:
        - name: q
          type: string
          in: query
          description: movie name
          required: true
        - name: sortBy
          type: string
          in: query
          default: "rotten_tomatoes"
          enum: ["rotten_tomatoes", "audience_score"]
          description: sort movies by rotten_tomatoes or audience_score
          required: false

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification